### ISSUE TITLE
database error , 

### ISSUE THREAD

**Issue by stealth1134** [hicham-alsayed-ahmad/ecommerce-using-codeigniter-3#1]
when im importing shop.oline.sql this error always show
will you help me or update it .. thx

![error](https://cloud.githubusercontent.com/assets/13176323/8507792/b4cfe98a-2285-11e5-939a-75cde58df71c.png)

**Comment by hicham-alsayed-ahmad** [comment]
update your PHP version to 5.5.12 or more
