### ISSUE TITLE
Plz new backup database

### ISSUE THREAD

**Issue by cookiesze** [hicham-alsayed-ahmad/ecommerce-using-codeigniter-3#2]
shop-online
Plz new backup database
Static analysis:

3 errors were found during analysis.

Variable name was expected. (near " " at position 23)
Variable name was expected. (near " " at position 38)
Unrecognized statement type. (near "new" at position 0)
SQL query:

new file mode 100644 @@ -0,0 +1,232 @@ +++++++++ +SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO"

MySQL said: Documentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'new file mode 100644

@@ -0,0 +1,232 @@
+++++++++
+SET SQL_MODE = "NO_AUTO_VALUE_' at line 1

**Comment by tommyhawkdev** [comment]
#1064 Database Error
Please do change new backup (export) database. :( 👍 
Thank You

**Comment by tommyhawkdev** [comment]
I Just make a new databases to the Source Code Thank You for the free Source :) 👍 
Sorry for my language

**Comment by cookiesze** [comment]
@tommyhawk95 I need database Plz upload

**Comment by tommyhawkdev** [comment]
@cookiesze Done

**Comment by pasekb** [comment]
> @cookiesze Done

can you send me the database ? hehe
