### ISSUE TITLE
The requested URL /shop-online/ was not found on this server.

### ISSUE THREAD

**Issue by Gardezi1** [hicham-alsayed-ahmad/ecommerce-using-codeigniter-3#3]
Hello guys, 

I'm trying to run this project but it keeps on throwing this error. Please tell me what is it that I'm doing wrong. I've followed all the steps but still it's not working. Please help me out 

![image](https://cloud.githubusercontent.com/assets/13199724/24082457/b8ab81ec-0ce7-11e7-8e79-1e3a8b07d1cf.png)

**Comment by hicham-alsayed-ahmad** [comment]
Hello , Please Check your port local server is working fine 
btw try localhost:80/shop-online

**Comment by Gardezi1** [comment]
Sorry for the late reply.  the local server is working perfectly and I have tried shop-online but that does not works either

**Comment by hicham-alsayed-ahmad** [comment]
good day , 
done or not yet ?

**Comment by Gardezi1** [comment]
Well, I kind of stopped using it. 

I should have closed this ticket sorry about that

**Comment by hicham-alsayed-ahmad** [comment]
okay , no problem , feel free to open new ticket anytime you want
