### ISSUE TITLE
the error when inport database

### ISSUE THREAD

**Issue by liyuange2007** [hicham-alsayed-ahmad/ecommerce-using-codeigniter-3#4]
There are 3 errors when i import database,  what's the problem with it?
![image](https://user-images.githubusercontent.com/38851152/39417758-90e4a10a-4c80-11e8-907a-ab75ac706f51.png)

**Comment by felisane** [comment]
Hey Im having the same problem. Please let me know if you fixed already

**Comment by tommyhawkdev** [comment]
What version mysql did you use?

**Comment by felisane** [comment]
I’m using version 5
Hey thanks for your reply

Enviado do meu iPhone

No dia 23/08/2018, às 14:55, Tommy Hawk <notifications@github.com<mailto:notifications@github.com>> escreveu:


What version mysql did you use?

**Comment by tommyhawkdev** [comment]
Have you Fixed it or not yet, sir?

**Comment by hicham-alsayed-ahmad** [comment]
hello everyone , can you tell me if you still have this error or not .

thanks in advance .

**Comment by hicham-alsayed-ahmad** [comment]
closed as no body reply within 1 month
